version: "3.10"
services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z



# DOCKER COMPOSE ALLOWS FOR ME TO NOT NEET TO CREATE A NETWORK WHEN RUNNING DOCKER. IT HAPPENS AUTOMATICALLY
# docker-compose up   or with -d for detached
# ctrl-c to quit the run
# docker-compose down to properly quit it