version: "3.10"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.6
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data:rw
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck: # optional, so Compose knows when ES is “ready”
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    #restart: unless-stopped


# DOCKER COMPOSE ALLOWS FOR ME TO NOT NEET TO CREATE A NETWORK WHEN RUNNING DOCKER. IT HAPPENS AUTOMATICALLY
# docker-compose up   or with -d for detached
# ctrl-c to quit the run
# docker-compose down to properly quit it